workflows:
  android-workflow:
    name: Android Build
    environment:
      groups: []
    scripts:
      - name: Find and build
        script: |
          find . -name "pubspec.yaml" -exec dirname {} \; | head -1 | xargs -I {} cd {} && flutter pub get && flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
