workflows:
  android-workflow:
    name: Android Build
    environment:
      groups: []
    scripts:
      - name: Build Android APK
        script: |
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
